version: "3.5"

volumes:
  modules:

services:
  kc:
    image: cnafsd/eosc-kc:latest
    environment:
      TZ: UTC
      KEYCLOAK_USER: admin
      KEYCLOAK_PASSWORD: admin
      KEYCLOAK_LOGLEVEL: DEBUG

    command: -c standalone.xml -b 0.0.0.0 --debug *:1044

    volumes:
      - ..:/code
      - ./standalone.xml:/opt/jboss/keycloak/standalone/configuration/standalone.xml
      - ../theme/target/eosc-kc-theme.jar:/opt/jboss/keycloak/standalone/deployments/eosc-kc-theme.jar
      - ../metadata-store/target/keycloak-saml-metadata-store.jar:/opt/jboss/keycloak/modules/it/infn/sd/keycloak-saml-metadata-store/main/keycloak-saml-metadata-store.jar
      - ../metadata-store/src/main/resources/module.xml:/opt/jboss/keycloak/modules/it/infn/sd/keycloak-saml-metadata-store/main/module.xml

    ports:
      - "8081:8080"
      - "1044:1044"
